fixed 64 bit compilation in windows. fixed a bug with the nae of shared library in windows better error checking in the installation procedures
git-svn-id: svn://svn.code.sf.net/p/flora/src/trunk@965 0877669f-6caa-400d-a9c2-f8e882ed57a8

diff --git a/flora2/floraconfig b/flora2/floraconfig
--- a/flora2/floraconfig
+++ b/flora2/floraconfig
@@ -25,25 +25,40 @@ if [ -z "$PROLOG" ] ; then
     exit 1
 else
     echo ""
-    echo "+++++ Using prolog engine: $PROLOG"
+    echo "+++++ Using Prolog engine: $PROLOG"
     echo ""
 fi
 
 # Generate the files that contain the Prolog & Flora installation directories
 # Generates runflora file that can be used to run flora
-(echo "[flrdepstest]." | $PROLOG) || xsbinstallerror=true
+
+($PROLOG -e "halt." 2>&1) > /dev/null || xsbinstallerror=true
 if test -n "$xsbinstallerror" ; then
     echo ""
-    echo "+++++ XSB is not configured or its sources have not been installed"
+    echo "+++++ Engine $PROLOG failed to start:"
+    echo "+++++    XSB has not been configured properly"
     echo ""
     exit 1
 fi
 
-(echo "['flrconfig']." | $PROLOG) || florausageerror=true
-if test -n "$florausageerror" ; then
+($PROLOG -e "[flrdepstest]. halt." 2>&1) > /dev/null || xsbsourceserror=true
+if test -n "$xsbsourceserror" ; then
     echo ""
-    echo "+++++ Usage:"
-    echo "+++++   floraconfig path-for-/XSB/bin/xsb"
+    echo "+++++ XSB sources do not seem to have been installed"
     echo ""
     exit 1
+fi
+
+$PROLOG -e "[flrconfig]. halt." || florausageerror=true
+if test -n "$florausageerror" ; then
+    echo ""
+    echo "+++++ Failed to configure FLORA-2"
+    echo "+++++ Please report to flora-users@lists.sf.net and include the log"
+    echo ""
+    exit 1
+else
+    echo ""
+    echo "+++++ All is well: run FLORA-2 using the script"
+    echo "+++++    ./runflora"
+    echo ""
 fi
