revamped installation. simplified. added setflora. needs more testing.
git-svn-id: svn://svn.code.sf.net/p/flora/src/trunk@961 0877669f-6caa-400d-a9c2-f8e882ed57a8

diff --git a/flora2/setflora b/flora2/setflora
--- a/flora2/setflora
+++ b/flora2/setflora
@@ -8,17 +8,25 @@ fi
 
 # Generate the files that contain the Prolog & Flora installation directories
 # Generates runflora file that can be used to run flora
-rm -fr .makeflora.tmp
-(echo "['flrdepstest']." | $PROLOG) \
-    || (echo "++Please reconfigure or reinstall XSB.";  touch .makeflora.tmp)
-if test -f .makeflora.tmp ; then
-    rm -rf .makeflora.tmp
+(echo "[flrdepstest]." | $PROLOG) || error=true
+if test -n "$error" ; then
+    echo ""
+    echo "+++++ XSB is not configured or its sources have not been installed"
+    echo ""
     exit 1
 fi
 
-(echo "['flrconfig']." | $PROLOG) \
-    || (echo "Usage:  makeflora all full-path-to-prolog"; touch .makeflora.tmp)
-if test -f .makeflora.tmp ; then
-    rm -rf .makeflora.tmp
+if test "$2" != compiling -a ! -f genincludes/flrtable.flh ; then
+    echo ""
+    echo "+++++ FLORA-2 must be first compiled with the makeflora command"
+    echo ""
+    exit 1
+fi
+
+(echo "['flrconfig']." | $PROLOG) || error=true
+if test -n "$error" ; then
+    echo ""
+    echo "++++ Usage:  setflora full-path-to-prolog"
+    echo ""
     exit 1
 fi
